import React, { useState } from "react";
import { AppProps } from "next/app";
import Head from "next/head";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { ThemeProvider } from "@/utils";

import "../styles/index.scss";
import { ColorCycleProvider } from "@/utils/hooks/useCycleColors";

const App = (props: AppProps) => {
  const { Component, pageProps } = props;
  const [queryClient] = useState(() => new QueryClient());

  return (
    <>
      <QueryClientProvider client={queryClient}>
        <Head>
          <title>dan-cv</title>
          <meta name="viewport" content="initial-scale=1, width=device-width" />
          <meta name="description" content="Generated by Create Next Stack." />
        </Head>
        <ColorCycleProvider>
          <ThemeProvider>
            <Component {...pageProps} />
          </ThemeProvider>
        </ColorCycleProvider>
      </QueryClientProvider>
    </>
  );
};

export default App;
